services:
  python-client:
    build:
      context: .
      args:
        ROS_IMAGE: ros:lyrical-ros-base
    network_mode: host
    environment: &ros_env
      ROS_DISTRO: lyrical
      RMW_IMPLEMENTATION: rmw_zenoh_cpp
      ZENOH_CONFIG_OVERRIDE: mode="client";connect/endpoints=["tcp/172.31.1.252:7447"]
      SERVICE_NAME: /pgwaam/id2_rpi4/Canon_EOS_6D/capture
    command: python3 /usr/local/bin/pgwaam_capture_client.py

  ros2-cli:
    build:
      context: .
      args:
        ROS_IMAGE: ros:lyrical-ros-base
    network_mode: host
    environment:
      <<: *ros_env
    command: /usr/local/bin/pgwaam_capture_cli.sh
